#############################################################################
## 1. OPENAPI
#############################################################################
openapi: 3.0.2

#############################################################################
## 2. INFO
#############################################################################
info:
  version: 1.0.0
  title: MonE Private EMSP (Event Message Streaming Platform) APIs Common Schema (Type) Definitions
  contact:
    name: MonE Product Development
    
  license:
    name: GNU AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  description: |
    <!-- Note that this description is a MARKDOWN Block -->

    **This Open API specification does NOT contain any valid PATHS/OPERATIONS!!!. It ONLY contains COMMON SCHEMA (TYPE) DEFINITIONS referred by other API specifications.**

    Thus, in this context COMMON SCHEMA (TYPE) DEFINITIONS mean shared entity data models or baseline objects that can be reused with or without extension.

#############################################################################
## 3. SERVERS
#############################################################################
servers:
  - url: https://{environment}.monetizehub.io:{port}/private/COMMON_TYPE_DEFINITION
    description: The production API server
    variables:
      environment:
        enum:
          - 'dev'
          - 'test'
          - 'staging'
          - ''
        default: 'dev'
      port:
        enum:
          - '443'
          - '8443'
        default: '443'
      version:
        default: 'v1'

#############################################################################
## 4. PATHS
#############################################################################
paths:
  /readMe:
    get:
      summary: This is a placeholder nouse operation. (to bypass Swagger UI limitation of a specification with ONLY data models without operation)
      operationId: readMe
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: string


#############################################################################
## 5. COMPONENTS
#############################################################################
components:

#############################################################################
## 5.x. SECURITY SCHEMES
#############################################################################
  securitySchemes:
    JWT_Bearer:
      type: http
      scheme: bearer 
      bearerFormat: JWT
    IAM_OAuth:
      type: oauth2
      description: |
        **OAuth Grant Type: Password Credentials**
      flows:
        password:
          tokenUrl: https://iam.monetizehub.io/oauth/v1/token
          scopes:
            write:resources: modify resources
            read:resources: read resources
    



#############################################################################
## 5.x. RESPONSES
#############################################################################

  responses:

    Response400:
      description: |
        Bad Request<br><br>

      content:
        'application/json':
          schema:
            type: object
            $ref: "#/components/schemas/EmspErrorContext"

    Response404:
      description: |
        Not Found<br><br>

      content:
        'application/json':
          schema:
            type: object
            $ref: "#/components/schemas/EmspErrorContext"

    Response500:
      description: |
        Internal Server Error<br><br>

      content:
        'application/json':
          schema:
            type: object
            $ref: "#/components/schemas/EmspErrorContext"     

    Response504:
      description: |
         Timeout<br><br>

      content:
        'application/json':
          schema:
            type: object
            $ref: "#/components/schemas/EmspErrorContext"  



#############################################################################
## 5.x. SCHEMA DEFINITIONS
#############################################################################
  schemas:

#############################################################################





#############################################################################
## 5.x. EXTERNAL COMMON DATA TYPE REFERENCES
#############################################################################
    


#############################################################################
## 5.x. EXTERNAL COMMON API TYPE REFERENCES
#############################################################################
    EmspErrorContext:
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_private_type_schemas.yaml#/components/schemas/EmspErrorContext'

#############################################################################
## 6. SECURITY
#############################################################################
security:
  - JWT_Bearer: []
  - IAM_OAuth: []    

#############################################################################
## 7. TAGS
#############################################################################


#############################################################################
## 8. EXTERNAL DOCS
#############################################################################
externalDocs:
  description:
    Find more information here.
  url: https://monetizehub.io/docs/home/






#############################################################################
#############################################################################