#############################################################################
## 1. OPENAPI
#############################################################################
openapi: 3.0.2

#############################################################################
## 2. INFO
#############################################################################
info:
  version: 1.0.0
  title: EMchg_Offline
  contact:
    name: MonE Product Development
    
  license:
    name: GNU AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  description: |
    <!-- Note that this description is a MARKDOWN Block -->

    **PRIVATE MESSAGING API SPECIFICATION:**
      * **Reference Point Name:** EMchg*
      * **API Name:** EMchg_Offline-Event Message Bus API

#############################################################################
## 3. SERVERS
#############################################################################
servers:
  - url: https://{environment}.monetizehub.io:{port}/private
    description: The production API server
    variables:
      environment:
        enum:
          - 'dev'
          - 'test'
          - 'staging'
          - ''
        default: 'dev'
      port:
        enum:
          - '443'
          - '8443'
        default: '443'
      version:
        default: 'v1'

tags:
  - name: "CH_FMF"
    description: "API: [EMSP <-> CH_FMF]"



#############################################################################
## 4. PATHS
#############################################################################
paths:
  /eventMessageBus/topic/chargingFmf/event:

    get:
      summary: 
        Read offline charging request
      operationId: Read-CH_FMF
      tags:
        - CH_FMF

      responses:
        200:
          description: "Success"

          content:
            'application/json':
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/FMF_Input_Event"

        400:
          $ref: "#/components/responses/Response400"
        404:
          $ref: "#/components/responses/Response404"
        500:
          $ref: "#/components/responses/Response500"
        504:
          $ref: "#/components/responses/Response504"

  /eventMessageBus/topic/chargingMtmf/event:

    post:
      summary:
        Publish Converted MonE CDS-Charging Data Stream Base (Uncharged, MonE Templated NOT applied)

      operationId: Post-CH_FMF
      tags:
        - CH_FMF

      requestBody:
        description: MonE Charging Data Stream (MCDS)
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FMF_Output_Event"

      responses:
        202:
          description: "No Content in Response / Event Message Published"
        400:
          $ref: "#/components/responses/Response400"
        500:
          $ref: "#/components/responses/Response500"
        504:
          $ref: "#/components/responses/Response504"



#############################################################################
## 5. COMPONENTS
#############################################################################
components:

#############################################################################
## 5.x. SECURITY SCHEMES
#############################################################################
  securitySchemes:
    JWT_Bearer:
      type: http
      scheme: bearer 
      bearerFormat: JWT
    IAM_OAuth:
      type: oauth2
      description: |
        **OAuth Grant Type: Password Credentials**
      flows:
        password:
          tokenUrl: https://iam.monetizehub.io/oauth/v1/token
          scopes:
            write:resources: modify resources
            read:resources: read resources



#############################################################################
## 5.x. RESPONSES
#############################################################################

  responses:

    Response400:
      $ref:  '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_private_emsp_api_schemas.yaml#/components/responses/Response400'
    Response404:
      $ref:  '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_private_emsp_api_schemas.yaml#/components/responses/Response404'
    Response500:
      $ref:  '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_private_emsp_api_schemas.yaml#/components/responses/Response500'
    Response504:
      $ref:  '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_private_emsp_api_schemas.yaml#/components/responses/Response504'


#############################################################################
## 5.x. SCHEMA DEFINITIONS
#############################################################################
  schemas:

#############################################################################
## 5.x. CHARGING DATA MODEL DEFINITIONS
#############################################################################






#############################################################################
## 5.x. EVENT MODEL DEFINITIONs
#############################################################################


    FMF_Input_Event:
      $ref: "#/components/schemas/Event_Charging_FMF_Input"

    FMF_Output_Event:
      description:
        Output Event for CH_FMF

      allOf:
        - $ref: "#/components/schemas/Event"
        - type: object
          properties:
            payload: 
              type: array
              items:
                $ref: "#/components/schemas/CDSBase"



#############################################################################
## 5.x. MODEL HELPERs
#############################################################################


#############################################################################
## 5.x. EXTERNAL EMSP API REFERENCES
#############################################################################

    Event_Charging_FMF_Input:
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_charging_type_schemas.yaml#/components/schemas/Event_Charging_FMF_Input'

    CDSBase:
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_charging_type_schemas.yaml#/components/schemas/CDSBase'

#############################################################################
## 5.x. EXTERNAL COMMON DATA TYPE REFERENCES
#############################################################################

    Entity:
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_tmforum_openapi_schemas.yaml#/components/schemas/Entity'
    EntityRef:
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_tmforum_openapi_schemas.yaml#/components/schemas/EntityRef'
    RelatedEntityRef:
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_tmforum_openapi_schemas.yaml#/components/schemas/RelatedEntityRef'
    Characteristic:  
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_tmforum_openapi_schemas.yaml#/components/schemas/Characteristic'


    Event:
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_private_type_schemas.yaml#/components/schemas/Event'
    Collection:  
      $ref: '/INTERFACES/API-SPECIFICATION/YAML/PRIVATE/common_private_type_schemas.yaml#/components/schemas/Collection'



#############################################################################
## 5.x. EXTERNAL COMMON API TYPE REFERENCES
#############################################################################



#############################################################################
## 6. SECURITY
#############################################################################
security:
  - JWT_Bearer: []
  - IAM_OAuth: []    

#############################################################################
## 7. TAGS
#############################################################################

#############################################################################
## 8. EXTERNAL DOCS
#############################################################################
externalDocs:
  description:
    Find more information here.
  url: https://monetizehub.io/docs/home/



#############################################################################
#############################################################################